name: Sync to Hugging Face
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Pehle git ko pehchan batayen (Automation ke liye zaroori hai)
          git config --global user.email "rehman3740377@example.com"
          git config --global user.name "remi-zafar"
          
          # Is line mein 'my-devops-pipeline' ko apne Hugging Face Space ke asli naam se badal dena agar wo mukhtalif hai
          git push --force https://swen213:$HF_TOKEN@huggingface.co/spaces/swen213/my-devops-pipeline main